### ISSUE TITLE
Add way to build the project

### ISSUE THREAD

**Issue by Swarthon** [HenryDane/Asterisk#17]
First of all, I find your project very interesting, sadly I found it quite difficult to compile.
Is it possible to add a way to build the project ? Something like CMake or Autoconf.
If you agree, I can help you by making it myself.

**Comment by HenryDane** [comment]
Yes I would love to have this -- this game is made with SFML for the graphics. As far as I know it would be very simple to create a Makefile for this, and to list all of the DLLs, etc that need to be pointed to. I do not really want to do this myself as I already am using an IDE so I very much appreciate your offer.

**Comment by Swarthon** [comment]
It is fixed with the following pull request #19.
Tell me if it is okay.

**Comment by HenryDane** [comment]
I merged your pull request. I looked good to me, and I assume you tested it successfully, so I'm gonna go ahead and close this issue. Thanks very much for the help.

**Comment by HenryDane** [comment]
So we just moved the project to `C` from `C++`. Would you mind fixing the CMake file to work with CSFML and `C` instead of just SFML and `C++`? It would be greatly appreciated.

**Comment by Swarthon** [comment]
No problem, just check the pull request I have made

**Comment by HenryDane** [comment]
Thanks so much for the help!
