### ISSUE TITLE
Module System

### ISSUE THREAD

**Issue by artillect** [HenryDane/Asterisk#8]
Add a system similar to Nier:Automata's module system (at least what I think it works like).

**Comment by HenryDane** [comment]
Could you provide more detail? I have never played Nier:Automata and I hope I never will. 
I was hoping for an explanation of the game mechanics and a short list of modules.

**Comment by artillect** [comment]
https://nierautomata.wiki.fextralife.com/System+Chips

This is a list of the upgrades in the game, many of which are preinstalled in the player character. They are enabled, disabled, attached, and removed, via an in-game UI.

What I'm thinking is that we create a module system where they can be affected somewhat by combat (damaged, destroyed, temporarily disabled), providing more interest to combat. Maybe an EMP weapon could temporarily disable a certain number of systems.

Upgrades I've already thought up:

Auditory Replication System - takes sensory information from outside ship and recreates it as sound, providing auditory feedback for the pilot. Somewhat useful but more of a neat demonstration of what the module system can do. Disabling it would eliminate all sound outside of the ship, and would muffle the sound of the ship's weapons and systems, as if the sound is only passing through the atmosphere of the ship and the hull of the ship. All we'd really need to do is a high-pass filter on whatever sound is going on, and stop playing sounds occuring outside of the ship (shouldn't be insanely hard but I don't know the capabilities of the audio chip).

Navigational Computer - provides assistance in making a FTL jump. Maybe lets you select destination star systems instead of requiring that you locate them yourself and input the coordinates manually.

Various other modules improving various systems such as shields, warp system, weaponry, armor, and control could be useful and easily designed.

**Comment by artillect** [comment]
Another little module I just thought up:

Short Range FTL system - allows for very short FTL jumps, on the order of 10s of meters. Usable for dodging in combat and allowing for further mobility.

**Comment by HenryDane** [comment]
That sounds like a really good idea. I will add these to the ship, but the character himself will obviously not have these. Still, I really like idea, and the auditory one sounds really cool.

**Comment by artillect** [comment]
That's the idea

**Comment by HenryDane** [comment]
Module support exists. To define a module, simply edit the `void add_module(module_t module)` and `void remove_module(module_t module)` functions inside `modules.c`. There one can find a switch-case block. Each module has an integer type. Simply add a case in both functions defining how to remove/add the module, and all is well.
